    DELETE a 
    FROM PRD_DB_RDV.T_OPRT_REFERENCE_L a
       , PRD_DB_STG.M_OPRT_REFERENCE_L b 
    WHERE b.DWH_SRC_SYSTEM_ID    = a.DWH_SRC_SYSTEM_ID 
      AND b.DWH_OPRT_ID_PRNT     = a.DWH_OPRT_ID_PRNT
      AND b.DWH_OPRT_ID_CHLD     = a.DWH_OPRT_ID_CHLD
      AND b.DWH_OPRT_REF_TYPE_ID = a.DWH_OPRT_REF_TYPE_ID 
      AND b.SRC_ACTN_TYPE        = 'D';